apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: main-vmstack
spec:
  selectAllByDefault: true
  scrapeInterval: 20s
  image:
    tag: v1.131.0
  remoteWrite:
  - url: http://vmsingle-main-vmstack.monitoring.svc:8428/api/v1/write
