apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: main-vmstack
spec:
  image:
    tag: v1.131.0
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
